---
title       : Forbes List of Billionaires 2014/2015
subtitle    : Age Distribution
author      : ZeroStack
job         : 
framework   : io2012        # {io2012, html5slides, shower, dzslides, ...}
highlighter : highlight.js  # {highlight.js, prettify, highlight}
hitheme     : tomorrow      # 
widgets     : []            # {mathjax, quiz, bootstrap}
mode        : selfcontained # {standalone, draft}
knit        : slidify::knit2slides
---

## Description

The shiny app I built can be used to explore age distribution of the forbes list of billionaires for the years 2015 and 2014.

## Details

- The shiny app can be found here: https://zerostack.shinyapps.io/appdp
- Accompanying github repo: https://github.com/ZeroStack/jhu_developingdataproducts

--- .class #id 

## Datset List 2015

```{r echo = FALSE, quiet = TRUE}

data <- read.csv('forbes.data.csv', sep = ",", header = TRUE)
data <- data[data$time == "2015",]
data[1:10,]

```

--- .class #id 

## Forbes Age Distribution 2015

```{r echo = FALSE, quiet = TRUE}
data <- read.csv('forbes.data.csv', sep = ",", header = TRUE)
plot <- ggplot(data, aes(x = age, y = networthb)) + geom_bar(stat = "identity") + xlab("Age in Years") + ylab("Bn Net Worth (US$)")
plot

```

--- .class #id 

## Thank You!



